version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    restart: always
    ports:
      - "9200:9200"
      - "9300:9330"
    networks:
      - elastic
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.9.3
    restart: always
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge